### ISSUE TITLE
error field type in Client object - expire_time

### ISSUE THREAD

**Issue by ap1w1** [iwatkot/py3xui#23]
When you pass expiry_time to the Client, it ignores it. Also, it ignores limit_ip

```
expiry_time = datetime.now() + timedelta(days=3)
expiry_time = datetime.timestamp(expiry_time) * 1000

print(int(expiry_time)) # RETURN -> 1728828171603

new_client = Client(id=uid, email=name,
                        enable=True,
                        expiry_time=int(expiry_time))

await async_api.client.add(server['inbound_id'], [new_client])

print(new_client) # RETURN  -> email='429' enable=True id='037e2ef9-0f3b-405a-af2e-6284c451b2ac' inbound_id=None up=0 down=0 expiry_time=0 total=0 reset=0 flow='' limit_ip=0 sub_id='' tg_id='' total_gb=0
```
![image](https://github.com/user-attachments/assets/c5d4b53c-445f-4bc9-86db-762ed995cb54)

**Comment by iwatkot** [comment]
@ap1w1, hello!

This behavior is described in the FAQ: https://github.com/iwatkot/py3xui/discussions/11

Sincerely

**Comment by iwatkot** [comment]
@ap1w1, hello again!

Sorry, I misunderstood the question the first time, so I'm coming back to you with an update.
The problem was that the populate by name option was not enabled for the Client model, as a result, the attributes had to be specified as expiryTime. In the latest release, this error has been fixed and everything should work correctly.

Best Regards
